version: "3.2"

networks:
  webshop:
    driver: bridge

services:
  service-discovery-server:
    image: nu.westlin.webshopkotlin/discovery-server:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - service-discovery-server
    ports:
      - 8761:8761

  core:
    image: nu.westlin.webshopkotlin/core:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - core
    ports:
      - 8080:8080
    depends_on:
      - service-discovery-server
      - customer
      - product
      - order

  customer:
    image: nu.westlin.webshopkotlin/customer:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - customer
    depends_on:
      - service-discovery-server

  product:
    image: nu.westlin.webshopkotlin/product:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - product
    depends_on:
      - service-discovery-server

  order:
    image: nu.westlin.webshopkotlin/order:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - order
    depends_on:
      - service-discovery-server

