version: "3.2"

networks:
  webshop:
    driver: bridge

services:
  service-discovery-server:
    image: nu.westlin.webshopkotlin/discovery-server:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - service-discovery-server
    ports:
      - 8761:8761

  core-service:
    image: nu.westlin.webshopkotlin/core-service:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - core-service
    ports:
      - 8080:8080
    depends_on:
      - service-discovery-server
      - customer-service
      - product-service
      - order-service

  customer-service:
    image: nu.westlin.webshopkotlin/customer-service:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - customer-service
    depends_on:
      - service-discovery-server

  product-service:
    image: nu.westlin.webshopkotlin/product-service:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - product-service
    depends_on:
      - service-discovery-server

  order-service:
    image: nu.westlin.webshopkotlin/order-service:0.1-SNAPSHOT
    networks:
      webshop:
        aliases:
          - order-service
    depends_on:
      - service-discovery-server

