spring.application.name: product

server.port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
