spring.application.name: customer-service

server.port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#  ribbon:
#    serverListRefreshInterval: 1000
#ribbon:
#  serverListRefreshInterval: 1000