spring.application.name: service-discovery-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring.cloud.loadbalancer.ribbon.enabled: false

#logging.level.com.netflix:
#  eureka: OFF
#  discovery: OFF