spring.application.name: product-service

server.port: 8082

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
