spring.application.name: core

#spring.cloud.loadbalancer.ribbon.enabled: false

# todo petves: customer -> customer-service
customerService.baseUrl: http://customer
productService.baseUrl: http://product
orderService.baseUrl: http://order


eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://service-discovery-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
#core:
#  ribbon:
#    serverListRefreshInterval: 1000
#ribbon:
#  serverListRefreshInterval: 1000