spring.application.name: core-service

customerService.baseUrl: http://customer-service
productService.baseUrl: http://product-service
orderService.baseUrl: http://order-service

eureka:
  client:
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#core:
#  ribbon:
#    serverListRefreshInterval: 1000
#ribbon:
#  serverListRefreshInterval: 1000